openapi: "3.0.0"
info:
  version: 0.0.1
  title: Open Order Cancellation Open API
  description: Endpoints for handling the open order cancellations
paths:
  /openapi/bos/v1/openordercancellations:
    post:
      summary: Places an open order cancellation request
      requestBody:
        required: true
        content:
          application/json:
            schema:
             $ref: '#/components/schemas/OpenOrderCreationRequest'
                
      responses:
        '201':
          description: Successfully placed open order cancellation request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenOrderCancellationResponse'
        '400':
          description: When model validation fails
        '500':
          description: Internal server error occurred
          
      x-application-visibility: saxo-only
      x-network-visibility: internal
      x-required-permissions: personal-write 
      
  /openapi/bos/v1/openordercancellations/{OpenOrderCancellationConfigId}:
    patch:
      summary: Update Open Order Cancellation
      operationId: updateOpenOrderCancellation
      parameters: 
        - name: OpenOrderCancellationConfigId
          in: path
          required: true
          schema:
            type: string
        - name: OpenOrderUpdateRequest
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/OpenOrderCreationRequest'
      responses:
        '204':
          description: Successfully updated open order cancellation
        '400':
          description: Model validation fails
        '500':
          description: Internal server error occurred
      x-application-visibility: saxo-only
      x-network-visibility: internal
      x-required-permissions: personal-write 
      
    delete:
      summary: Update Open Order Cancellation
      operationId: deleteOpenOrderCancellation
      parameters: 
        - name: OpenOrderCancellationConfigId
          in: path
          required: true
          schema:
            type: string
        - name: OpenOrderDeletionRequest
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/OpenOrderDeletionRequest'
      responses:
        '204':
          description: Successfully updated open order cancellation
        '400':
          description: Model validation fails
        '500':
          description: Internal server error occurred
      x-application-visibility: saxo-only
      x-network-visibility: internal
      x-required-permissions: personal-write 
  /openapi/bos/v1/assetblockings/stocktransfers:
    get:
      summary: Fetches asset blocking stock data
      operationId: fetchStocktransfers
      parameters: 
        - name: StockTransferId
          in: query
          description: The stock transfer id
          required: false
          schema:
            type: string
        - name: Client
          in: query
          description: The Client id
          required: false
          schema:
            type: string
        - name: InstrumentUIC
          in: query
          description: The InstrumentUIC
          required: false
          schema:
            type: string
        - name: SortColumn
          in: query
          description: Column name that needs to be considered for filter
          required: false
          schema:
            type: string
            enum: 
              - StockTransferId
              - InstrumentUIC
              - BlockingAction
              - Client
              - BlockedQuantity
        - name: SortOrder
          in: query
          description: The SortOrder
          required: false
          schema:
            type: string
            enum:
             - ASC
             - DESC
      responses:
        '200':
          description: Successfully fetched blocked data
          content:
            application/json: 
              schema:
                $ref: "#/components/schemas/BlockingStockTransfer"
        '400':
          description: Model validation fails
        '500':
          description: Internal server error occurred
      x-application-visibility: saxo-only
      x-network-visibility: internal
      x-required-permissions: personal-read
   
  /openapi/bos/v1/assetblockings/corporateactions:
    get:
      summary: Fetches asset blocking stock data
      operationId: fetchCorporateactions
      parameters: 
        - name: CorporateActionId
          in: query
          description: The CorporateActionId
          required: false
          schema:
            type: string
        - name: Client
          in: query
          description: The Client id
          required: false
          schema:
            type: string
        - name: InstrumentUIC
          in: query
          description: The InstrumentUIC
          required: false
          schema:
            type: string
        - name: Exdate
          in: query
          description: Exdate
          required: false
          schema:
            type: string
            format: date-time
        - name: Paydate
          in: query
          description: Paydate
          required: false
          schema:
            type: string
            format: date-time
        - name: DeadlineDate
          in: query
          description: DeadlineDate
          required: false
          schema:
            type: string
            format: date-time
        - name: OwnerID
          in: query
          description: OwnerID
          required: false
          schema:
            type: string
            format: date-time
        - name: SortColumn
          in: query
          description: Column name that needs to be considered for filter
          required: false
          schema:
            type: string
            enum: 
              - CorporateActionId
              - InstrumentUIC
              - BlockingAction
              - Client
              - BlockedQuantity
              - ExDate
              - PayDate
              - DedalineDate
        - name: SortOrder
          in: query
          description: The SortOrder
          required: false
          schema:
            type: string
            enum:
             - ASC
             - DESC
      responses:
        '200':
          description: Corporate Actions data
          content:
            application/json: 
              schema:
                $ref: "#/components/schemas/BlockingCoac"
        '400':
          description: Model validation fails
        '500':
          description: Internal server error
      x-application-visibility: saxo-only
      x-network-visibility: internal
      x-required-permissions: personal-read
   
  /openapi/bos/v1/assetblockings/corporateaction/download:
    get:
      summary: Fetches asset blocking stock data
      operationId: downloadCorporateActions
      parameters: 
        - name: CorporateActionId
          in: query
          description: The CorporateActionId
          required: false
          schema:
            type: string
        - name: Client
          in: query
          description: The Client id
          required: false
          schema:
            type: string
        - name: InstrumentUIC
          in: query
          description: The InstrumentUIC
          required: false
          schema:
            type: string
        - name: Exdate
          in: query
          description: Exdate
          required: false
          schema:
            type: string
            format: date-time
        - name: Paydate
          in: query
          description: Paydate
          required: false
          schema:
            type: string
            format: date-time
        - name: DeadlineDate
          in: query
          description: DeadlineDate
          required: false
          schema:
            type: string
            format: date-time
        - name: OwnerID
          in: query
          description: OwnerID
          required: false
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Downloads file
          content:
            image/png:
              schema:
                type: string
                format: binary
                
            application/octet-stream:
              schema:
                type: string
                format: binary
          
        '400':
          description: Model validation fails
        '500':
          description: Internal server error
      x-application-visibility: saxo-only
      x-network-visibility: internal
      x-required-permissions: personal-read 

  /openapi/bos/v1/assetblockings/stocktransfer/download:
    get:
      summary: Downloads asset blocking stock data
      operationId: downloadtocktransfers
      parameters: 
        - name: StockTransferId
          in: query
          description: The stock transfer id
          required: false
          schema:
            type: string
        - name: Client
          in: query
          description: The Client id
          required: false
          schema:
            type: string
        - name: InstrumentUIC
          in: query
          description: The InstrumentUIC
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Downloads file
          content:
            image/png:
              schema:
                type: string
                format: binary
                
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          description: Model validation fails
        '500':
          description: Internal server error occurred
      x-application-visibility: saxo-only
      x-network-visibility: internal
      x-required-permissions: personal-read 
      
  /openapi/bos/v1/assetblockings/{BlockingId}:
    patch:
      summary: Update asset blocking
      operationId: updateAssetBlocking
      parameters: 
        - name: BlockingId
          in: path
          required: true
          schema:
            type: string
        - name: BlockedQuantity
          in: query
          required: true
          schema:
            type: string
        - name: Requester
          in: query
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Successfully updated asset blocking
        '400':
          description: Model validation fails
        '500':
          description: Internal server error occurred
      x-application-visibility: saxo-only
      x-network-visibility: internal
      x-required-permissions: personal-write 
components:
  schemas:
    AssetBlockingCreateRequest:
      type: object
      properties:
        RequestReferenceId:
          type: string
        BlockCodeReferenceID:
          type: string
        BlockingAction:
          type: string
          maxLength: 1
        Client:
          type: string
        AttainKey:
          type: string
        InstrumentUIC:
          type: string
        ProductCode:
          type: string
        BlockedQuantity:
          type: string
        PositionCutOffDate:
          type: string
        BlockCode:
          type: string
        BlockingIDReference:
          type: string
        Requester:
          type: string
          
    BlockingStockTransfer:
      type: object
      required:
        - RowNo
      properties:
        StockTransferId:
          type: string
        Position:
          type: string
        AttainKey:
          type: string
        BlockCode:
          type: string
        BlockedQuantity:
          type: number
        BlockingAction:
          type: string
        BlockingId:
          type: string
        BlockingIDReference:
          type: string
        Client:
          type: string
        CounterpartId:
          type: string
        InstrumentUIC:
          type: string
        OwnerID:
          type: string
        PositionCutOffDate:
          type: string
          format: date-time
        ProcessingDate:
          type: string
          format: date-time
        ProcessingStatus:
          type: string
        ProductCode:
          type: string
        Requester:
          type: string
        RequestReferenceId:
          type: string
        UnblockedQuantity:
          type: number
        TotalRowsCount:
          type: integer
        RowNo:
          type: integer
          description: row number
        
    BlockingCoac:
      type: object
      properties:
        AttainKey:
          type: string
        BlockCode:
          type: string
        BlockedQuantity:
          type: number
        BlockingAction:
          type: string
        BlockingId:
          type: string
        BlockingIDReference:
          type: string
        Client:
          type: string
        CounterpartId:
          type: string
        InstrumentUIC:
          type: string
        OwnerID:
          type: string
        PositionCutOffDate:
          type: string
          format: date-time
        ProcessingDate:
          type: string
          format: date-time
        ProcessingStatus:
          type: string
        ProductCode:
          type: string
        Requester:
          type: string
        RequestReferenceId:
          type: string
        UnblockedQuantity:
          type: string
        CorporateActionId:
          type: string
        EntitledPosition:
          type: number
        EligiblePosition:
          type: number
        ElectedQuantity:
          type: number
        LockingReason:
          type: string
        ExDate:
          type: string
        PayDate:
          type: string
        DeadlineDate:
          type: string
        TotalRowsCount:
          type: integer
        RowNo:
          type: integer
          
    OpenOrderCreationRequest:
      type: object
      required: 
        - DateTypeId
        - OrderDeletionTypeId
        - PriceSeed
        - User
        - CorporateActionTypeId
        - EventTypeId
      properties:
        DateTypeId:
          type: integer
          description: "This indicates open order cancel trigger date i.e. when the placed request will get triggered.Few examples of date types are 1 for Ex-date, 2 for Record Date, 3 for PayDate, and 4 for ClientDeadlineDate. For more date types refer to lookups end point."
          example: 1
        OrderDeletionTypeId:
          type: integer
          description: "This indicates order deletion type. Few examples are 1 for Never delete orders, 2 for Delete if change is more than 20%, and 3 for Always delete orders. For more order deletion types refer to lookups end point."
          example: 1
        PriceSeed:
          type: number
          description: "The closing price of a security."
          example: 12.34
        User:
          type: string
          description: "Initials of the user who raised the request."
          example: "KIRM"
        CorporateActionTypeId:
          type: integer
          description: "Types of action initiated by corporate such as: 10 for Cash Dividend, 11 for Dividend Option, and 34 for Interest. For more corporate action types refer to lookups end point."
          example: 11
        EventTypeId:
          type: integer
          description: "There are 3 types of events: 1 for Choice, 2 for Mandatory and 3 for Voluntary. For more information refer to lookups end point."
          example: 1
        InstrumentSubTypeId:
          type: integer
          description: "Sub assets type. For more information refer to lookups end point. You should provide product id to fetch this data."
          
    OpenOrderUpdateRequest:
      type: object
      required: 
        - DateTypeId
        - PriceSeed
        - User
        - InstrumentSubTypeId
      properties:
        DateTypeId:
          type: integer
          description: "This indicates open order cancel trigger date i.e. when the placed request will get triggered.Few examples of date types are 1 for Ex-date, 2 for Record Date, 3 for PayDate, and 4 for ClientDeadlineDate. For more date types refer to lookups end point."
          example: 1
        PriceSeed:
          type: number
          description: "The closing price of a security."
          example: 12.34
        User:
          type: string
          description: "Initials of the user who raised the request."
          example: "KIRM"
        InstrumentSubTypeId:
          type: integer
          description: "Sub assets type. For more information refer to lookups end point. You should provide product id to fetch this data."
        
    OpenOrderDeletionRequest:
      type: object
      required: 
        - User
      properties:
        User:
          type: string
          description: "Initials of the user performing the delete action."
          example: "KIRM"
      
    OpenOrderLookupRequest:
      type: object
      required: 
        - FieldGroup
      properties:
        FieldGroup:
          type: string
          enum: 
            - DateTypes
            - EventTypes
            - InstrumentSubTypes
            - OrderDeletionTypes
            - ProductCodes
            - CorporateActionTypes
          description: This field represents the field group the user has requested.
          example: DateTypes
        DependentId:
          type: string
          description: "This field represents the identity of an existing field group data based on which we want to fetch its subtypes. It's optional. It's required when the requested field group is of InstrumentSubTypes."
          
    OpenOrderCancellationResponse:
      type: object
      properties:
        ResultValue:
          type: string
          description: "This field contains status message of the user action."